### ISSUE TITLE
pystacked crashes when there is one predictor

### ISSUE THREAD

**Issue by markeschaffer** [aahrens1/pystacked#3]
Example (changing the learner doesn't matter):

sysuse auto, clear
pystacked price mpg, type(reg)

Results in:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 236, in run_stacked
  File "C:\Anaconda3\lib\site-packages\sklearn\ensemble\_stacking.py", line 684, in fit
    return super().fit(X, y, sample_weight)
  File "C:\Anaconda3\lib\site-packages\sklearn\ensemble\_stacking.py", line 147, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs)(
  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sklearn\ensemble\_base.py", line 39, in _fit_single_estimator
    estimator.fit(X, y)
  File "C:\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 341, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "C:\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 303, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "C:\Anaconda3\lib\site-packages\joblib\memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "C:\Anaconda3\lib\site-packages\sklearn\compose\_column_transformer.py", line 503, in fit_transform
    self._check_n_features(X, reset=True)
  File "C:\Anaconda3\lib\site-packages\sklearn\base.py", line 352, in _check_n_features
    n_features = X.shape[1]
IndexError: tuple index out of range
r(7102);

**Comment by aahrens1** [comment]
Thanks -- Should be fixed now.
